/* Populate database with sample data. */

INSERT INTO animals(NAME, DOB, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES ('Charmander', '2020-02-08', 0, false, -11.0);
INSERT INTO animals(NAME, DOB, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES ('Plantmon', '2021-02-08', 2, true, -5.7);
INSERT INTO animals(NAME, DOB, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES ('Squirtle', '1993-04-02', 3, false, -12.13);
INSERT INTO animals(NAME, DOB, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES ('Angemon', '2005-06-12', 1, true, -45.0);
INSERT INTO animals(NAME, DOB, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES ('Boarmon', '2005-06-07', 7, true, 20.4);
INSERT INTO animals(NAME, DOB, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES ('Blossom', '1998-10-13', 3, true, 17.0);
INSERT INTO animals(NAME, DOB, ESCAPE_ATTEMPTS, NEUTERED, WEIGHT_KG) VALUES ('Ditto', '2022-05-14', 4, true, 22.0);

INSERT INTO owners(FULL_NAME, AGE) VALUES ('Sam Smith', 34);
INSERT INTO owners(FULL_NAME, AGE) VALUES ('Jennifer Orwell', 19);
INSERT INTO owners(FULL_NAME, AGE) VALUES ('Bob', 45);
INSERT INTO owners(FULL_NAME, AGE) VALUES ('Melody Pond', 77);
INSERT INTO owners(FULL_NAME, AGE) VALUES ('Dean Winchester', 14);
INSERT INTO owners(FULL_NAME, AGE) VALUES ('Jodie Whittaker', 38);

INSERT INTO species(SPECIE_NAME) VALUES ('digimon');
INSERT INTO species(SPECIE_NAME) VALUES ('pokemon');

UPDATE animals SET SPECIES_ID=1 WHERE name LIKE '%mon';
UPDATE animals SET SPECIES_ID=2 WHERE SPECIES_ID IS NULL;

UPDATE animals SET owner_id=2 WHERE name='Agumon';
UPDATE animals SET owner_id=3 WHERE name='Gabumon' OR name='Pikachu';
UPDATE animals SET owner_id=4 WHERE name='Devimon' OR name='Plantmon';
UPDATE animals SET owner_id=5 WHERE name='Charmander' OR name='Squirtle' OR name='Blossom';
UPDATE animals SET owner_id=6 WHERE name='Angemon' OR name='Boarmon';

INSERT INTO vets (NAME, AGE, DATE_OF_GRADUATION) VALUES ('William Tatcher', 45, '2000-04-23');
INSERT INTO vets (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Maisy Smith', 26, '2019-01-17');
INSERT INTO vets (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Stephanie Mendez', 64, '1981-05-04');
INSERT INTO vets (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Jack Harkness', 38, '2008-06-08');

INSERT INTO SPECIALTIES(SPECIES_ID, VET_ID) VALUES (1, 2);
INSERT INTO SPECIALTIES(SPECIES_ID, VET_ID) VALUES (2, 3);
INSERT INTO SPECIALTIES(SPECIES_ID, VET_ID) VALUES (2, 4);

INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (1, 4, '2021-02-24'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (2, 2, '2019-12-21'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (2, 1, '2020-08-10'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (2, 2, '2021-08-07'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (3, 3, '2019-09-29');
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (4, 4, '2020-10-03');
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (4, 4, '2020-11-04'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (5, 2, '2019-01-24'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (5, 2, '2019-05-15'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (5, 2, '2020-02-27'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (5, 2, '2020-08-03'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (6, 3, '2020-05-24'); 
INSERT INTO VISITS(ANIMAL_ID, VET_ID, DATE_VISITED) VALUES (6, 1, '2021-01-11'); 