/* Database schema to keep the structure of entire database. */

CREATE DATABASE vet_clinic;

\c vet_clinic;

CREATE TABLE animals (
    ID SERIAL PRIMARY KEY, 
    NAME TEXT, 
    DOB DATE, 
    ESCAPE_ATTEMPTS INT, 
    NEUTERED BOOLEAN, 
    WEIGHT_KG DECIMAL
);

ALTER TABLE animals ADD SPECIES TEXT;

CREATE TABLE OWNERS (
  ID SERIAL PRIMARY KEY,
  FULL_NAME TEXT,
  AGE INT
);

CREATE TABLE SPECIES (
  ID SERIAL PRIMARY KEY,
  SPECIE_NAME TEXT
);

ALTER TABLE animals DROP species;
ALTER TABLE animals ADD species_id INT REFERENCES SPECIES(ID);
ALTER TABLE animals ADD owner_id INT REFERENCES OWNERS(ID);
